databases:
  - name: keyed-db
    databaseName: keyed
    user: keyed_admin
    plan: free

services:
  - type: web
    name: keyed-backend
    env: docker
    plan: free
    rootDir: Assets
    envVars:
      # Указываем Render, какой порт слушать внутри контейнера
      - key: PORT
        value: "8080"

      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: keyed-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        value: keyed_admin
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: keyed-db
          property: password
      - key: POSTGRES_DB
        value: keyed
      - key: POSTGRES_USER
        value: keyed_admin
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: keyed-db
          property: password
      - key: POSTGRES_PORT
        value: "5432"
      - key: JWT_SECRET
        value: KeyedVaultDevSecretChangeMeInProduction32Chars
      - key: JWT_EXPIRATION_MS
        value: "86400000"