databases:
  - name: keyed-db
    databaseName: keyed
    user: keyed_admin
    plan: free

services:
  - type: web
    name: keyed-backend
    env: docker
    plan: free
    rootDir: Assets
    envVars:
      - key: PORT
        value: "10000"

      # Render сам возьмет точный рабочий внутренний URL базы и подставит сюда
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: keyed-db
          property: connectionString

      - key: SPRING_DATASOURCE_USERNAME
        value: keyed_admin

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: keyed-db
          property: password

      - key: JWT_SECRET
        value: KeyedVaultDevSecretChangeMeInProduction32Chars
      - key: JWT_EXPIRATION_MS
        value: "86400000"