spring.application.name=Assets (Emir_Comfci24)
server.port=10000

# ????????? JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ?????? ?? ?????
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Auth
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}